---
- name: Routine maintenance — Updates and system cleanup
  hosts: "{{ target_hosts | default('windows11') }}"
  gather_facts: false
  roles:
    - role: lineadicomando.win_workman.dispatcher
      vars:
        win_workman_tasks:
          - "wol"
          - "logoff"
          - "lock"
          - "chkdsk"
          - "wim"
          - "sfc"
          - "optimize"
        win_workman_mode_title: "Maintenance in progress"
        win_workman_mode_text: "Do not turn off the PC. Maintenance is almost complete."

- name: Routine maintenance — Unlock workstations
  hosts: "{{ target_hosts | default('windows11') }}"
  gather_facts: false
  roles:
    - role: lineadicomando.win_workman.dispatcher
      vars:
        win_workman_tasks:
          - "lock-off"
          - "restart"
